name: Format and Fix

on:
  push:
    branches: ["master", "main"]
    paths:
      - "main/**"
  pull_request:
    paths:
      - "main/**"
  # 手動でも実行可能にする
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find ./main -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) \
          | xargs clang-format -i

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto format with clang-format"
          file_pattern: "main/**/*.c main/**/*.cpp main/**/*.h main/**/*.hpp"
